spring.application.name=firstVersion
spring.datasource.url=jdbc:postgresql://localhost:5432/equipment_db
spring.datasource.username=your_username
spring.datasource.password=your_password
jwt.secret-key=your_jwt_secret_key_here_replace_this_value
jwt.expiration=86400000

spring.jpa.hibernate.ddl-auto=update